import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

import { ChallengeLanding } from '@/features/rooms/ChallengeLanding';

/**
 * A challenge link (spec §22).
 *
 * Inside the site group on purpose — unlike a room, this is a front door. Someone
 * arriving from a chat app has probably never heard of Puzzly, so the header and
 * footer are exactly what they need once they have decided whether to play.
 *
 * The challenge itself is fetched on the client: it is short-lived, personal to
 * the link, and pointless to render on a server or cache anywhere.
 */

export const metadata: Metadata = {
  title: 'A challenge for you',
  description: 'Someone solved a puzzle and thinks you cannot beat their time.',
  // Ephemeral by design — these expire, and an indexed dead link helps nobody.
  robots: { index: false, follow: false },
};

interface ChallengePageProps {
  params: Promise<{ id: string }>;
}

export default async function ChallengePage({ params }: ChallengePageProps) {
  const { id: raw } = await params;
  const id = decodeURIComponent(raw).trim();

  // Ids are generated by `createId`, so anything with punctuation or an absurd
  // length is a mangled link rather than a lookup worth making.
  if (!/^[A-Za-z0-9_-]{4,64}$/.test(id)) notFound();

  return <ChallengeLanding id={id} />;
}
